# -*- coding: utf-8 -*-
"""dspl.cw.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSDgNwDAdDCuM9mTi11ECxzwE7nBeDyA
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the dataset into a DataFrame
df = pd.read_csv('/content/UNdata_Export_20250504_174459230.csv')

# Check the first few rows to verify
df.head()

# Check for missing values in the dataset
missing_values = df.isnull().sum()

# Show the number of missing values for each column
missing_values

# Check the data types of each column
df.dtypes

# Fill the missing value in the 'Value' column with the mean of the column
df['Value'].fillna(df['Value'].mean(), inplace=True)

# Check if the missing value is now filled
df.isnull().sum()

# Save the cleaned dataset to a new CSV file in Google Colab
df.to_csv('/content/Cleaned_SriLanka_Data.csv', index=False)

from google.colab import files

# Download the saved file
files.download('/content/Cleaned_SriLanka_Data.csv')